/** @format */

export const ErrorCode = {
  AUTH_EMAIL_ALREADY_EXISTS: "AUTH_EMAIL_ALREADY_EXISTS",
  AUTH_PHONE_NUMBER_ALREADY_EXISTS: "AUTH_PHONE_NUMBER_ALREADY_EXISTS",
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
  AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
  AUTH_USER_ALREADY_EXISTS: "AUTH_USER_ALREADY_EXISTS",

  AUTH_NOT_FOUND: "AUTH_NOT_FOUND",
  AUTH_TOO_MANY_ATTEMPTS: "AUTH_TOO_MANY_ATTEMPTS",
  AUTH_UNAUTHORIZED_ACCESS: "AUTH_UNAUTHORIZED_ACCESS",
  AUTH_TOKEN_NOT_FOUND: "AUTH_TOKEN_NOT_FOUND",
  AUTH_EMAIL_NOT_VERIFIED: "AUTH_EMAIL_NOT_VERIFIED",
  AUTH_VERIFICATION_LINK_EXPIRED: "AUTH_VERIFICATION_LINK_EXPIRED",

  // Access Control Errors
  ACCESS_UNAUTHORIZED: "ACCESS_UNAUTHORIZED",

  // Validation and Resource Errors
  VALIDATION_ERROR: "VALIDATION_ERROR",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  ACCOUNT_DELETION_INELIGIBLE: "ACCOUNT_DELETION_INELIGIBLE",

  RESOURCE_CONFLICT: "RESOURCE_CONFLICT",

  // Referral / attribution errors
  REFERRAL_CODE_INVALID: "REFERRAL_CODE_INVALID",
  REFERRAL_CODE_DISABLED: "REFERRAL_CODE_DISABLED",
  REFERRAL_CODE_EXPIRED: "REFERRAL_CODE_EXPIRED",
  REFERRAL_CODE_EXHAUSTED: "REFERRAL_CODE_EXHAUSTED",
  REFERRAL_AUDIENCE_MISMATCH: "REFERRAL_AUDIENCE_MISMATCH",
  REFERRAL_SELF: "REFERRAL_SELF",
  ALREADY_ATTRIBUTED: "ALREADY_ATTRIBUTED",
  ATTRIBUTION_WINDOW_CLOSED: "ATTRIBUTION_WINDOW_CLOSED",

  // Partner API errors
  PARTNER_UNAUTHORIZED: "PARTNER_UNAUTHORIZED",
  PARTNER_FORBIDDEN_SCOPE: "PARTNER_FORBIDDEN_SCOPE",
  PARTNER_SIGNATURE_INVALID: "PARTNER_SIGNATURE_INVALID",
  IDEMPOTENCY_KEY_REQUIRED: "IDEMPOTENCY_KEY_REQUIRED",
  IDEMPOTENCY_KEY_REUSED: "IDEMPOTENCY_KEY_REUSED",
  IDEMPOTENCY_IN_PROGRESS: "IDEMPOTENCY_IN_PROGRESS",
  DUPLICATE_EXTERNAL_REF: "DUPLICATE_EXTERNAL_REF",
  DUPLICATE_SUBMISSION: "DUPLICATE_SUBMISSION",

  // System Errors
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  MAIL_DELIVERY_FAILED: "MAIL_DELIVERY_FAILED",
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
